const swaggerUi = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
        swagger: '2.0',
        info: {
            title: 'Hackaton Data vs Corona virus',
            version: '1.0.0',
            description: 'Hackaton Data vs Corona virus API with autogenerated swagger doc'
        },
        basePath: '/api',
        securityDefinitions: {
            ApiKeyAuth: {
                type: 'apiKey',
                in: 'header',
                name: 'X-API-Key',
            }
        },
        security: [
            {},
            {ApiKeyAuth: []}
        ]
    },
    apis: ['./docs/*.yaml', './api/controllers/*.js']
};

const specs = swaggerJsDoc(options);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
};